#!/usr/bin/env python
# -*- encoding: UTF-8 -*-

"""
@File   : verify.py
@Time   : 2020/11/7 20:19
@Author : yd
@Version: 1.0
@ToDo    : 基于超级鹰的网站验证码识别 ：https://www.chaojiying.com
"""

import requests


class Verify:
    """
    基于超级鹰的网站验证码识别 ：https://www.chaojiying.com
    """

    def __init__(self, username, password, soft_id='96001'):
        self.username = username
        # 避免明文外泄，可以使用md5后的字符串
        # password = password.encode('utf8')
        self.password = password
        # self.password = md5(password).hexdigest()
        self.soft_id = soft_id
        self.base_params = {
            'user': self.username,
            'pass2': self.password,
            'softid': self.soft_id,
        }
        self.headers = {
            'Connection': 'Keep-Alive',
            'User-Agent': 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)',
        }

    def post_picture(self, code_type, file_base64=None, im='../data/imgs/verify_img.png'):
        """
        :param code_type: 验证码类型 参考:http://www.chaojiying.com/price.html
        :param file_base64: 图片格式，
        :param im: 图片字节
        :return:
        """
        params = {
            'codetype': code_type,
        }
        params.update(self.base_params)
        # 如果不是base64图片，就去掉保存好的验证码图片
        if file_base64 is None or file_base64 == "":
            # 读取图片为二进制
            im = open(im, 'rb').read()
            files = {'userfile': ('verify_img.png', im)}
            try:
                r = requests.post('http://upload.chaojiying.net/Upload/Processing.php',
                                  data=params, files=files,
                                  headers=self.headers)
                rjson = r.json()
                if rjson['pic_str'] is None or str(rjson['pic_str']) == '':
                    return None
                else:
                    return str(rjson['pic_str'])
            except Exception as e:
                return None
        else:
            # base64图片，直接传base64
            params.update({"file_base64": file_base64})
            try:
                r = requests.post('http://upload.chaojiying.net/Upload/Processing.php',
                                  data=params,
                                  headers=self.headers)
                rjson = r.json()
                if rjson['pic_str'] is None or str(rjson['pic_str']) == '':
                    return None
                else:
                    return str(rjson['pic_str'])
            except Exception as e:
                return None

    def report_error(self, im_id):
        """
        im_id:报错题目的图片ID
        """
        params = {
            'id': im_id,
        }
        params.update(self.base_params)
        r = requests.post('http://upload.chaojiying.net/Upload/ReportError.php', data=params, headers=self.headers)
        return r.json()


if __name__ == '__main__':
    verify = Verify('wuqingfqng', '6e8ebd2e301f3d5331e1e230ff3f3ca5', '96001')
    # base64图片解析
    # print(verify.PostPic(1902,file_base64="R0lGODdhlgA8AIcAAP7+/gICAujo6NfX1/Pz8xcXFycnJ1dXV8fHx0dHR3Z2djY2NoeHh2hoaKam\nppeXl7e3t7i4uKqqqj09PcLCwgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAlgA8AEAI/wABCBxI\nsKDBgwgTKlzIsKHDhxAjSpy4UACCAQMgCCDQ4MCBACANIABAsqTJkyhRRgjAsqUBBAAAPABAs6bN\nmzhz6tzJk+aDAEALMDAQIECCAgUMFAiw4AGAp1ABOABAtWpVBwUCBGAgQACAr2DDigXrIIDZs2cN\nRCAAAECAt3DfGiAAoK7duwQMJFhQIIDfABIACB5MuDDhAQASK17MuHFiAg4MGGhwwMGDCAAyawZw\nIIADAKBDAxAAoLTp06UHCDgQIAGA17BfIxgQoYAEALgRGAgQwECBBwEEABhOvDjxAgGSKwDAnDkB\nBQMASJcuoEGBAAEWGHBwAID37woQHP8IEKABgPPoBQBYz769+/ftGVBgAMHBggAFDgDYz78/f4AC\nBgAgCOBBgAANGBhwAMDhQwAEEgQYIADARYwABAgA0BHAgAAhRQYQAMDkSQQJBABg2dJlywEBAigg\nAMAmAAUBdO4MMADATwAEAhhYEOCAgAEEACxl2tTpU6hMBQQIsCDA1QAOAGzluhUBALBhwwo4UCAC\nALRp1a5lywDAW7hvBRQIUNeAAQYA9O4V0CDAXwUEAAwmPPhBgwcIHEQA0BhBAMiRITcAUBnAAAML\nHBAA0NmzZwEARI8mXdo0aQEGAgQwwKCAAgIAZM+mPVuABAEDBgDg3dv3b+DBgQtw4ED/QQDkCQAs\nZw5AAADo0aVPpw59AIMDAQIcaBAAwPfvAyBAAFDe/Hn06dWvZ9/e/Xv48eXPp1/f/n38+fXv5x9f\nAEAFAQYSJJgggQEGABYyZDigQIIGASYaIADgIkaMCAJwDBABAMiQIkc6CGDgwQADAQIgAODyJUwB\nDwDQbLAgQYCcORcYKJCgAYMBAIYOJUABANKkSpcyXRohANQABhIEAGD1KoABAbYaEADgK1gABACQ\nLWs2ANoABgCwbQtggIECCQIEmEAgQYC8BSIAEDCAAIDAggcDGGDYQIADFBAAaOz4MYAGBwIEKBAg\ngAIIEgBw5ixgQYIAogMcaADg9GkB/wgAsG7t+jVs1ggC0K4dAAKA3Lp38yYA4PdvBwkcQFgQ4HgB\nAwECFGAgAAD06NAlAKhuPUGA7NohAOju/Tt4AAgQAChv3kAAAgDWAxAQIIECAwHmByAA4D7+/PoP\nQBAAACAAgQMJFjRIMIKBAAsLBFAgAEBEiRMpAhAQAOMBBgIAdPTYEcGBAAESMCAAAGVKAAQAtGxJ\n4EAAmQESKBAAACdOAQYCBBgAAGhQoQAQBDCqAEBSAAoUJIjAYEGAAA8AVK3a4ECBAFsLDADwFWxY\nsWPJhlXgwECAAAsUPADwFu5bAQYCBBAAAG/evAgcSADwF3BgwQAEADB8GDGAAIsZB/8QAAByZAEB\nKFM2AABzZgEPAHT27DlBgQCjSQcAcBp16tQECABw/Rp2bNmzXQ8IkKBAgAAGBhBA8AABAOHDiRc3\nfhx58uQDFABw/hx6dOnTqVe3fh17du3buXf3/h18ePHbBQAYIACAAADr2bd3/x4+fAEMBgggAAB/\nfv37+ff3DxCAwIEECxo8iJDggAMNBAB4CDFiRAIREDBYkKDAgQIMEhgYAIAAAwcGFhR4ACClypUs\nVwposCCATJkMBAC4ifNmAAA8e/oEQCCCgQQBihotwIAAgKVMmzp9CvWpAAAEEBAAgBUAggkBGhwI\nwEDBgAEAygogACCt2rQEArh1q4D/AIC5dOvaBTBgAIC9AAQwMLBgQYEHBAAQOBAgseIADAA4fgwZ\nQAQDASobWBAgc4AFAgB4/gw6tAAApEubPo0awIMCAVq7bq1AAIDZEAI0KBBgwQAAvHsDEAAguHDh\nAxQUCBAgAYDlzJsPgCAAgIAEBgoceGBgQYAACxAA+A7+u4AA5MsPMEAAgPr17AEISCBggYMABxYQ\nAIAfP4EBCgIEANhgwEAABQ0WAJBQ4UKGDQU8kBBA4oIHBgBcxAhAwIEAEwgAABlSAACSJU0CUHDA\nQIAGAFy+dOkgwMwCCAAAGBBA506dAHz+BOozQoIAARYoQABAqVIBAgA8hVoggQAH/wscMEgAQOtW\nAQsOBAAboAEAsmUFAECbVu1atgAGBDDwgEEDAQoIAMCbFwADBwD8/gVAAMDgwQgcBAhQQDGDAwEc\nJyAAQPJkAAIIAMAMQACEAwE8ey7wgAAA0qVNmw4QYAEBAK1bIzAgAMDs2QoaGFiwIICBBAIA/AYe\nwMACAQCMHydAAMBy5s2dP18uQEECCAcCXA/AAMB27t29e4dQIMB4AwMQDBDA4MGABQEcABgAQP58\nAAQA3MfP4EAA/vwFAAQgcKAABgAOIkyocEGACQIAQAQwgEKDABYtNiAAYCPHjgQAgAwJgIIAACZP\nokypEoCABAwAODBwIMIAADZv4v/MOQCAgAA+AxRgAGAo0aEICgRgQAAA06ZMBRgAIBUAAQUBrl5V\nAGArVwIHAjAAIHYs2bEJAgR4AGAtAAIJAsCNWwAAXboPCgTIG6BAAwEA/gIGcAAA4cKGDyMGsCAA\n48YMAECOLHky5AEBAhygQAAA586dJQQwkAABgNKmSx8AoHo1gACuXxsAIHs2gQC2FyAAoHv3bgIL\nAgBXAGA4gAUNAhQoEIDBggUAngOAEGFAgQQBGADIrj27AADev4MPL947AgMJGgQIsKCAAwDu37tn\noEAAgPr26wtYYGAAgP7+AQIQOJCgQAEIACRUqHCAggIBIBqIAIBiRQAMCgTQ6AD/QEePACAQAACA\ngAABEAYMSHCgQACXARBAEACAZk2bNwEMALCTZ0+fP306EBCAKNEDAJAmRUoAQYIABRQAkDpVqgAB\nAQI8EACAAACvXwFAeACAbFmzZhMEULuWAAC3bwkIAAAAgoECAwgQiKCgAQC/fwELOBCAcIACDyBE\nALCYMeMBAwBEljyZcmXLkyUkCBCgQIIEDgQAED0aAAEAp1GnVr2adWvXBAYMeGAggAQAtwEgUNAA\nQG/fv4EHF94bQgEAx5EnV76ceXPnz6FHlz6denXr17Fn176de3fv38GHFz+efHnz59GnV7+effvl\nBAZEAIAgQAADAQwgALCff3///wABCBxIsKCAAQ8CKAxQYMEBBQAiSpxIsaLFixgzatzIUeIBBQgI\nHDDQQAAAAQMkFEiwIMABADBjypxJM+aACQFy6pQAoGdPAREACB1KlCgBCQcSIHiAAIDTp1CjSp1K\ntSrUAQ0CaA1Q4ACDAQIAiB1LVoCBBA8KBCgwAAGDAw8GMBgwAECBBAEMDADAt6/fv3wVBFCAQMIB\nAwEkAFjMuLEEAgAiAxgQAYCABwECKECQoMCBBQsONIiAYAABAKhTq17NurVr1ggOBJgd4ECDBQUC\nNEDAAIDv378JKAhAPICBBwQAKF/OXDkBCQUOEABAvToAAQCyax8QoLv3ABAAiP8fTx7AAQAIFBxo\n0CCAe/cLGjgQAKC+ffsEBADYz7+/f4AABA4kWFCBgQMFDCxQIIAAAAMFCjiIcOABAIwZBQDg2LEj\nggAhCwRQAMDkSZQpTw4AQEBCAJgxYS444GBBAJw5cQLg2dMnzwBBhQZdkAABAKRJlS4F4IAAAKhR\npU6lCqDBgwBZtQaQkCCAAgYLAowdewDAWbQABABg27ZtBAMB5B4AUNfuXbwABjQwUCDAX8ABHAgA\nULgwgwCJFReYIADAY8iRETRoMGBAggABDAwA0NmzZwESEAAgXRoAAQQAVK9m3bq1gAQBZM8uAMD2\n7QEJDhQokGAAAODBATgAUNz/uHEBDQoECHAAwHPozxEkCFAdwYAA2Q88KHCAwYABAMSPJz/AAIQE\nAQIIkCAAwHv48d8XUBDAfoACDgDs5+8gAMAAAQokEHBgAICECSUAaOjwIcSICAwEqFgxAQIAGjcC\nOBAgQAEAIkeKHADgJMqUCBwUCNAAAMyYMBkEqLnAAQABCgIEKLAgAYMDAgAQLWqU6IEEAQIIEDAA\nANSoUqEKONDggYEAEwQEAOD1q4MHBwKQXaCAAIC0aRMAaOv2Ldy4AxAECLDgQYMFAgDw7QvgQIAG\nAAYTBiAAAOLEihErOBAgAAEAkicDEFAgwIIBAgAAIODgQIAEChYwUADgNOrU/6gRBGgdoAGA2LEh\nPABg+/aDAAEUTGgAQQECAMKHB1gQ4HgACACWLycgAAD06NKnUweAIMACBQwcCCgA4Dt4AAMMRABg\n/jwABADWs0cQoIECBgwUBCgQIAAEAPr3AyCAACAAAAQiPBAgIEBChQEcAHD4EOJDAgwCBHAAAGPG\nBgEAdPSYgEEAkQccGABwEuWABQsCBBgAAGZMCABo1rR5EydNAg0CHEhg4MACBgCIFgUwAAEApUsB\nEADw9KkDCAkCFAgQYIGCBAECGKBAAEBYsQAcCABw9qyAAGvZBhAAAG5cuXIFIEggAEBevQkYAPDr\nd4ABAw0UMCiwoAEAxYsHDP8gAAByZAAEBACwfBlzZs2XGQRQUCBA6AADAJQ2ffo0AQCrVx9IEMAA\nAwQEDhxoEAA37gEAePfmTWAAAOHCBShIEAB5gAQAmDd3/py5AADTqSsIAAFAdgAEEhgwEAA8+AcA\nyJc3f548gQgDALR3/x5+fAADDjQIYCBAfgQA+Pf3DxCAQAICABgEgCCAwgAFHAB4CECAAAcBDggA\nIACAxo0AEAD4+JFBgJEkFQgAgDLlBAQAWrp8+fJBgQAQANgEQCCAzp06BQD4CRTAAAcOBAgAgDQp\nAAYAmjp9CjWqAAULGCBwwGBAAgEAunr9+lUAgLEByjYQMEAAgLVsAQgIEED/gQMBAOraBTAAgF69\nCgL4/YsAgODBAAIkAIA4seLEBAIEKIAAgGQAEgoEuIz5AYDNmwN49nwggQMApEuTJgAgterVrFkT\nKAA7QAAEBBAAuI07t24BFBAYCBBggYIBAIobL97AQIEDAgA4f/48AIDp0wcwCIA9AAMBALp7HxAg\nwAMA5MubJ/8gQIAEAwC4BxBAQYMABQLYFwAgf34GCRYEABigwAEEAAweBDAAwEKGDR0+FGAgwMSJ\nCSgAwJhR40aMCQIEKGBgAACSJUkSeBCgQIEGAgC8hAmAAACaNR0EwJlTAQCePSMYCJBgAACiRY0O\nWBAggAEBAJwOCBDgwNQA/wEKOACQFQCCBw0KBAhgAMBYsmXNnkVLVkIAtm0XDAAQVy4AAgDs3r0r\noECAAgQA/AUcGMCAAQAMHzYsIAIAxo0BNAgQOUADCAIAXMacIMDmAAIAfAYNukAA0gUAnAagIMGC\nAwUCMGhQYAAA2gAYSBAggAEA3r17DyAAQPhw4sWNA2BA4EGBAM0VEAAQXTqABxAIAMCeHbuAAwcE\nAAAfXvz48RMAnEePXoGCAO3bA4AfH4CAAgHsKwCQX39+AgAAACTgwAABAAAGGIAQYOHCBxMAQIRI\nAADFihYpDgCgcSPHjh43NhjAIECBBgIGAEipMqUAAwkQAIgpM2aEAhEEAP/IqXMnz5wPAAANKlRA\ngKIBCjgwAGApUwADDASImmAAgKpWIwgAoHWrVgEJAoAFe0ABAwBmz6JNO4AAgLZu38KN+1bAAgUB\n7i4QIAAA3758JQQIcAABgMKGDQeYgAAA48aOGwsAIHky5ckRAmDOrAAA584AJAyQ0CBAAAQATp8e\n0AAA69atDwRYEGB2AAUNBADIrXs3AAIEBAAILnw48eLGIRQIEKBAggUHCACILn26hAcMBBAAoF3A\ngAEAvn8PEMABAQECBgwAIAAA+/bu3wNwUKBAgPoBIADIrx8AAgD+AQIYIAABAwAHESZMCCFAwwAF\nHBAwAIBiRYoCEADQuJGnY0ePHzk+KFAgQAAFAwgQALCSZcuWBADElDmTZk2bN2MaUADBQACfBAAE\nFToAQFGjR5EmRTqAgYIDBR4IQAABAgCrV7Fm1bqV61UHAcCGVQCALFkCAwYAULuWbVu3b+HGZTuA\nQQEHAxQoALCXb1+/fwEHFjyYcGG+BBA0UGwgAADHjyFHljyZcmXLlzFn1ryZc2fPn0GHFj2adGnT\np1GnVr2adevKAQEAOw==\n"))

    # 普通图片解析
    print(verify.post_picture(1902))
